apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# リソース
# Sample App Bのマニフェスト
resources:
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: sample-app-b
  newName: craksscaletozerotm6fic3o.azurecr.io/aks-scale-to-zero/sample-app-b-sample
  newTag: azd-deploy-1752830560
