apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-api
  namespace: scale-system
  labels:
    app.kubernetes.io/name: scale-api
    app.kubernetes.io/part-of: aks-scale-to-zero
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scale-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scale-api
        app.kubernetes.io/part-of: aks-scale-to-zero
    spec:
      serviceAccountName: scale-api-sa
      nodeSelector:
        agentpool: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: scale-api
          image: scale-api:initial
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
      securityContext:
        fsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
